### PR TITLE
:rocket: feat: add new inventories concept (#15)

### PR DESCRIPTION
**Pull request by mostafaghadimi**

### CODE REVIEW

**Review by ShAlireza — APPROVED** [review]

**Review by niyushabaghayi — APPROVED** [review]
Thanks @mostafaghadimi :purple_heart: 
Would you please contribute to Wiki in this regard as well? :))

**Comment by mostafaghadimi** [comment]
Of course! I prefer that these stuffs would be added to the roadmap and then the related content can be placed on wiki, as well.
Thank you for your insightful comment, @niyushabaghayi!

**Comment by iamdorsa** [comment]
Thank you for your suggestion to update the roadmap. I noticed that you proposed separating "Data Warehouse" into "Relational Data Warehouse" and "Modern Data Warehouse." Could you please explain the reasoning behind this distinctionc?

**Comment by mostafaghadimi** [comment]
Thank you for asking this valuable question, @iamdorsa. Relational Data Warehouse refers to when we only used the relational database as our single source of truth for both transactions and analytics. But, Modern Data Warehouse refers to the situation where we use the advantages of both relational data warehouse and data lake.

**Pull request merged**
